- name: Catalogue Setup
  hosts: all
  become: true
  vars:
    component: catalogue
  tasks:
    - name: NodeJS Setup
      ansible.builtin.import_tasks: nodejs.yml




#schema_type=mongodb
#source common.sh
#
#
#func_nodejs